### PR TITLE
Created optional functions to trigger per step

### PR DESCRIPTION
**Pull request by elroy910**
Not sure if the location of the triggers is the correct one but in our code we wanted to create a tour containing multiple tabs. So we highlighted the tabs, now by listening to the events from the tourService. Ideally it's better to have step specific triggers in the step it self, right? Therefore I thought about a before and after show, but also a before and after hide. This way before a step is shown or hidden we can trigger own pieces of code, like switchings tabs or mimic a click or event or something?

Feel free to discuss :) and thank you for the nice repository

### CODE REVIEW

**Comment by hakimio** [comment]
Hi @elroy910 
Thanks for the PR.
- There is already a way to listen to events using [event observables](https://hakimio.github.io/ngx-ui-tour/md-menu/API#events). Any extra events should be defined the same way.
- `yarn.lock` modification should not be part of the PR.
- Can you describe your use case for the new events in a bit more detail? Why can't you just use existing `stepShow$` and `stepHide$` events?

**Comment by elroy910** [comment]
Hi @hakimio 

I'm aware that there is indeed an event observable and we can listen to a couple of events. But I noticed while implementing this library, which I'm quite gratefull for, I was struggling to trigger application specific events when 'only' certain steps were shown or hidden.

For example to give you a use-case. You have multiple steps in your tour. And for example when you go from step 2 to 3 you want to fill in a form or change a piece of text or trigger a click event. You need to listen in the event observable or listen in stepShow$ or stepHide$ to first check if you go from step 2 to 3 to trigger those 'step specific' events. I did found the stepId but this would mean you need to do a lot of if-statements in your stepHide$ or stepShow$ when you want to trigger that step specific functionality.

My thought, by giving each step an optional event which is triggered before and after showing but also before and after hiding we have the step specific event functionalities in the steps it self! It's again just a thought but it would and can help out our application a lot.

Sorry about the yarn.lock, first time creating a MR like this. Just wanted to share my thoughts ;)

Greetings Leroy

**Comment by hakimio** [comment]
Sorry, but after some consideration, I think this is not a good addition to the library:
- I don't like having multiple ways to listen to tour events and I prefer observables to plain callback functions.
- Even with your examples, I don't see any real need for `after*` events.
- To get rid of step id checking boilerplate, you can introduce a custom RxJS operator to filter steps like the following:
```ts
import {filter, Observable, MonoTypeOperatorFunction} from 'rxjs';
import {StepChangeParams} from 'ngx-ui-tour-core';

export function filterSteps(id: string): MonoTypeOperatorFunction<StepChangeParams> {
    return (source: Observable<StepChangeParams>): Observable<StepChangeParams> => source.pipe(
        filter(stepChangeParams => {
            const step = stepChangeParams.step;

            return step.anchorId === id || step.stepId === id;
        })
    );
}

this.tourService.stepShow$
    .pipe(
        filterSteps('start.tour')
    )
    .subscribe(stepChangeParams => console.log(stepChangeParams.step));
```

**Comment by elroy910** [comment]
Hi,

I see what you mean, I indeed also like this approach. I do however think about the fact that, when a tour consists of let's say: 20 steps? Each step needs to make sure that before the 'spotlight' some values were set, or a certain event is triggered. You tent to write below multiple times for each step right? Each call with a seperate stepId. Let's also not forget to unsubscribe when we start a different tour with different steps. This means you can also get 20 subscribers.

`this.tourService.stepShow$
    .pipe(
        filterSteps('start.tour')
    )
    .subscribe(stepChangeParams => console.log(stepChangeParams.step));`

I like this approach, will try to think of a different way where we can get the best of both worlds.

**Comment by hakimio** [comment]
You can also create a custom RxJS operator which takes an array of step ids instead of a single id and use a filter like `stepIds.includes(step.stepId)` inside your custom operator.
To avoid having to manually unsubscribe, you can use `takeUntil()` operator:
```ts
this.tourService.stepShow$
    .pipe(
        filterSteps('start.tour'),
        takeUntil(this.tourService.end$)
    )
    .subscribe(stepChangeParams => console.log(stepChangeParams.step));
```

**Comment by elroy910** [comment]
Not sure if I understand correctly. You mean like searching for the correct event with the help of: `stepIds.includes(step.stepId) ` ? You mean like getting that specific event from a seperate property or list? How would it be that if there are multiple steps and each step has their own unique event or functionality that needs to be triggered, how are you storing those? 
Rather have them within the step, not? 

Good call on the takeUntil.!

**Comment by hakimio** [comment]
I just mean the following:
```ts
import {filter, MonoTypeOperatorFunction} from 'rxjs';
import {StepChangeParams} from 'ngx-ui-tour-core';

export function filterSteps(ids: string[]): MonoTypeOperatorFunction<StepChangeParams> {
    return source => source.pipe(
        filter(stepChangeParams => {
            const step = stepChangeParams.step;

            return ids.includes(step.anchorId) || ids.includes(step.stepId);
        })
    );
}

this.tourService.stepShow$
    .pipe(
        filterSteps(['start.tour', 'foo', 'bar', 'baz'])
    )
    .subscribe(stepChangeParams => console.log(stepChangeParams.step));
```

This allows you to target multiple steps at once.

**Comment by elroy910** [comment]
This I understand, but in my use-case each step has their own specific thing that needs to happen. So now I have for example 4 steps, which will go through the subscribe but what event is triggered? Where is that application specific event per step coming from? For example, for step: start.tour I want to make the <h1> tag color red and for the step: bar I want to trigger a click event?
Where is that specific piece of code put, or coming from?

**Comment by hakimio** [comment]
I don't really understand what you are asking. Maybe you can provide a code example of what you are doing and what doesn't work for you?

**Pull request closed without merging**
