### PR TITLE
Add ability to configurable space between the anchor element and back…

### PR DESCRIPTION
**Pull request by mivanyna**
…drop

### CODE REVIEW

**Comment by hakimio** [comment]
You are modifying `BackdropService` used by all tour UIs, but only fixing tour step position for `ng-bootstrap` UI. This has to be a universal solution which would work with all tour UIs.

**Comment by hakimio** [comment]
No, I don't have any simple universal solution and I don't know any volunteers willing to implement it for other UIs.

**Comment by mivanyna** [comment]
How we can have it for Ng bootstrap only?

**Comment by mivanyna** [comment]
Otherwise, the main issue for other UIs is that the tooltip arrow is not aligned with the backdrop border.
Maybe it's not a big issue?
Anyway, it's an optional config and shouldn't be critical for others UIs

**Comment by hakimio** [comment]
I do think it's an issue and people will complain about it.
If `ng-bootstrap` UI was the only one supported by this library, I would gladly merge this PR but the way it works now, it looks like this PR introduces a bug for other UIs while adding non-essential feature for `ng-bootstrap`.

**Comment by mivanyna** [comment]
Which bug do you mean? Can you describe it? Or you mean that arrow alignment?

Backdrop functionality is shared and it will work for all the UIs.

The only issue is that popover arrow is aligned to the anchor, not the backdrop border. And I don't think this one is critical.
If the user uses 2-4px it's not an issue at all I think.

**Comment by hakimio** [comment]
Step alignment with backdrop borders.

**Comment by mivanyna** [comment]
Btw, there is one potential issue with the workaround with padding/margin if I have a button(with some action - opening a modal or some section) and putting an anchor on the added parent element(with those styles applied) and have `nextOnAnchorClick: true` and if the user presses not on the button, but on the area between the button and backdrop - my tour get broken as the action is not done, but the tour is moved to next step

**Comment by hakimio** [comment]
I have added support for `backdropConfig.offset` for `md-menu`, `ng-bootstrap` and `tui-dropdown` tour UIs in the latest release. Check out [the release announcement](https://github.com/hakimio/ngx-ui-tour/releases/tag/v11.0.0) and thank you for your contribution.

**Comment by hakimio** [comment]
You are welcome 🙂

**Pull request closed without merging**
