### PR TITLE
Fix backdrop flickering

### PR DESCRIPTION
**Pull request by sokolovstas**
Without this check backdrop flickering on each step

### CODE REVIEW

**Comment by hakimio** [comment]
`closeSpotlight()` doesn't remove the backdrop, it only disables currently active anchor element highlighting - the whole screen becomes dimmed without any highlighted element.
`backdrop.close()` is used to disable backdrop entirely and it happens [here](https://github.com/hakimio/ngx-ui-tour/blob/277b3ebe3ed89af8336c0e609f4ed9f522ebb8b1/projects/ngx-ui-tour-core/src/lib/tour.service.ts#L564).

I can not see any backdrop flickering in the following demo project:
https://stackblitz.com/edit/angular-wau2z8?file=src%2Fapp%2Fui-tour-demo.component.ts

If you see flickering in this demo project or some other simple project, please open a new bug report with reproduction code and a video showing the flickering you experience.

**Comment by sokolovstas** [comment]
Oh I get it, I think I have this bug when set enableBackdrop on each step and don’t set it globally. I will try to reproduce it later and share demo.

**Comment by hakimio** [comment]
Unless you missed some steps, it shouldn't matter if it's set on every step separately or in step defaults.
Anyway, can you see that the backdrop elements are removed and re-added between tour steps in your case?

**Comment by sokolovstas** [comment]
I have seen that backdrop position is reset to zero and in another frame it will position to next step.

**Comment by sokolovstas** [comment]
Sorry for troubles, maybe this was something with browser or my app. I reinstall package and rebuild everything and it working fine now.

**Pull request closed without merging**
